apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:latest  # 백엔드 Docker 이미지 사용
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "mysql://root:password@mysql:3306/opensourcedb"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
